# Generated by Django 5.2.7 on 2025-11-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order_field', 'product_name']},
        ),
        migrations.AddField(
            model_name='product',
            name='order_field',
            field=models.SmallIntegerField(default=0),
        ),
    ]
