# Generated by Django 5.2.7 on 2025-11-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variations'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['order_field', 'product']},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order_field',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
