# Generated by Django 5.2.7 on 2025-11-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cartitem_options_cartitem_order_field_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='order_field',
        ),
    ]
