# Generated by Django 5.2.7 on 2025-11-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
