# Generated by Django 5.2.7 on 2025-11-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
    ]
